version: '3.9'
services:
  postgres:
    image: postgres:16.1
    env_file:
      - .env
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5433"
    volumes:
      - ./Database/database-script.sql:/docker-entrypoint-initdb.d/database-script.sql
    command: -p 5433
    networks:
        - app-network
    
  accounts.api:
    image: ${DOCKER_REGISTRY-}accountsapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
